name: CI/CD Sign Language Identifier

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar teste de import e inferência dummy
        run: |
          python -c "import torch; print('Torch OK:', torch.__version__)"
          # Exemplo: rodar plot_confusion se existir matriz
          python scripts/plot_confusion.py || echo 'Sem matriz de confusão, ignorado.'

  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test   

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir e publicar imagem Docker
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/sign-language-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

